// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// An App Store Connect accessibility declaration for a single device family of
/// an app. `device_family` is the ASC device-family value (e.g. `IPHONE`,
/// `IPAD`, `MAC`); `state` is the publication state (`DRAFT`, `PUBLISHED`,
/// `REPLACED`) when present. The nine `supports_*` flags declare which
/// accessibility features the app supports for that device family.
///
/// Note: the App Store Connect wire attribute for
/// [`Self::supports_differentiate_without_color`] is
/// `supportsDifferentiateWithoutColorAlone` (with an `Alone` suffix); the field
/// is named without the suffix here for the host's benefit.
class AccessibilityDeclarationInfo {
  final String id;
  final String deviceFamily;
  final String? state;
  final bool supportsAudioDescriptions;
  final bool supportsCaptions;
  final bool supportsDarkInterface;
  final bool supportsDifferentiateWithoutColor;
  final bool supportsLargerText;
  final bool supportsReducedMotion;
  final bool supportsSufficientContrast;
  final bool supportsVoiceControl;
  final bool supportsVoiceover;

  const AccessibilityDeclarationInfo({
    required this.id,
    required this.deviceFamily,
    this.state,
    required this.supportsAudioDescriptions,
    required this.supportsCaptions,
    required this.supportsDarkInterface,
    required this.supportsDifferentiateWithoutColor,
    required this.supportsLargerText,
    required this.supportsReducedMotion,
    required this.supportsSufficientContrast,
    required this.supportsVoiceControl,
    required this.supportsVoiceover,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      deviceFamily.hashCode ^
      state.hashCode ^
      supportsAudioDescriptions.hashCode ^
      supportsCaptions.hashCode ^
      supportsDarkInterface.hashCode ^
      supportsDifferentiateWithoutColor.hashCode ^
      supportsLargerText.hashCode ^
      supportsReducedMotion.hashCode ^
      supportsSufficientContrast.hashCode ^
      supportsVoiceControl.hashCode ^
      supportsVoiceover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccessibilityDeclarationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          deviceFamily == other.deviceFamily &&
          state == other.state &&
          supportsAudioDescriptions == other.supportsAudioDescriptions &&
          supportsCaptions == other.supportsCaptions &&
          supportsDarkInterface == other.supportsDarkInterface &&
          supportsDifferentiateWithoutColor ==
              other.supportsDifferentiateWithoutColor &&
          supportsLargerText == other.supportsLargerText &&
          supportsReducedMotion == other.supportsReducedMotion &&
          supportsSufficientContrast == other.supportsSufficientContrast &&
          supportsVoiceControl == other.supportsVoiceControl &&
          supportsVoiceover == other.supportsVoiceover;
}

/// An App Store age-rating declaration. Every content attribute is a raw ASC
/// enum string (e.g. `NONE` / `INFREQUENT_OR_MILD` / `FREQUENT_OR_INTENSE`)
/// passed through verbatim; the four `is_*` flags are booleans. All attributes
/// are optional and are `None` when absent from the response.
class AgeRatingDeclarationInfo {
  final String id;
  final String? alcoholTobaccoOrDrugUseOrReferences;
  final String? contests;
  final String? gamblingSimulated;
  final String? gunsOrOtherWeapons;
  final String? medicalOrTreatmentInformation;
  final String? profanityOrCrudeHumor;
  final String? sexualContentGraphicAndNudity;
  final String? sexualContentOrNudity;
  final String? horrorOrFearThemes;
  final String? matureOrSuggestiveThemes;
  final String? violenceCartoonOrFantasy;
  final String? violenceRealistic;
  final String? violenceRealisticProlongedGraphicOrSadistic;
  final bool? isAdvertising;
  final bool? isGambling;
  final bool? isUnrestrictedWebAccess;
  final bool? isUserGeneratedContent;
  final String? ageRatingOverrideV2;

  const AgeRatingDeclarationInfo({
    required this.id,
    this.alcoholTobaccoOrDrugUseOrReferences,
    this.contests,
    this.gamblingSimulated,
    this.gunsOrOtherWeapons,
    this.medicalOrTreatmentInformation,
    this.profanityOrCrudeHumor,
    this.sexualContentGraphicAndNudity,
    this.sexualContentOrNudity,
    this.horrorOrFearThemes,
    this.matureOrSuggestiveThemes,
    this.violenceCartoonOrFantasy,
    this.violenceRealistic,
    this.violenceRealisticProlongedGraphicOrSadistic,
    this.isAdvertising,
    this.isGambling,
    this.isUnrestrictedWebAccess,
    this.isUserGeneratedContent,
    this.ageRatingOverrideV2,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      alcoholTobaccoOrDrugUseOrReferences.hashCode ^
      contests.hashCode ^
      gamblingSimulated.hashCode ^
      gunsOrOtherWeapons.hashCode ^
      medicalOrTreatmentInformation.hashCode ^
      profanityOrCrudeHumor.hashCode ^
      sexualContentGraphicAndNudity.hashCode ^
      sexualContentOrNudity.hashCode ^
      horrorOrFearThemes.hashCode ^
      matureOrSuggestiveThemes.hashCode ^
      violenceCartoonOrFantasy.hashCode ^
      violenceRealistic.hashCode ^
      violenceRealisticProlongedGraphicOrSadistic.hashCode ^
      isAdvertising.hashCode ^
      isGambling.hashCode ^
      isUnrestrictedWebAccess.hashCode ^
      isUserGeneratedContent.hashCode ^
      ageRatingOverrideV2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgeRatingDeclarationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          alcoholTobaccoOrDrugUseOrReferences ==
              other.alcoholTobaccoOrDrugUseOrReferences &&
          contests == other.contests &&
          gamblingSimulated == other.gamblingSimulated &&
          gunsOrOtherWeapons == other.gunsOrOtherWeapons &&
          medicalOrTreatmentInformation ==
              other.medicalOrTreatmentInformation &&
          profanityOrCrudeHumor == other.profanityOrCrudeHumor &&
          sexualContentGraphicAndNudity ==
              other.sexualContentGraphicAndNudity &&
          sexualContentOrNudity == other.sexualContentOrNudity &&
          horrorOrFearThemes == other.horrorOrFearThemes &&
          matureOrSuggestiveThemes == other.matureOrSuggestiveThemes &&
          violenceCartoonOrFantasy == other.violenceCartoonOrFantasy &&
          violenceRealistic == other.violenceRealistic &&
          violenceRealisticProlongedGraphicOrSadistic ==
              other.violenceRealisticProlongedGraphicOrSadistic &&
          isAdvertising == other.isAdvertising &&
          isGambling == other.isGambling &&
          isUnrestrictedWebAccess == other.isUnrestrictedWebAccess &&
          isUserGeneratedContent == other.isUserGeneratedContent &&
          ageRatingOverrideV2 == other.ageRatingOverrideV2;
}

/// An App Store app category, with the ids of its subcategories. Deliberately
/// NON-recursive (UniFFI-friendly): `subcategory_ids` carries only the ids of the
/// nested subcategories, leaving the host to materialize the tree from a flat
/// list of [`AppCategoryInfo`] values if it needs the nesting.
class AppCategoryInfo {
  final String id;
  final List<String> subcategoryIds;

  const AppCategoryInfo({required this.id, required this.subcategoryIds});

  @override
  int get hashCode => id.hashCode ^ subcategoryIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppCategoryInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          subcategoryIds == other.subcategoryIds;
}

/// Cross-provider app metadata. Mirrors the Swift `AppInfo` from `StackProtocols`,
/// which is dissolved into the core (see RUST_CORE_PLAN.md §4).
///
/// Serializes camelCase (`bundleId`, not `bundle_id`) so persisted blobs match the
/// iOS-facing contract — see [`crate::service::sync::SyncService`].
class AppInfo {
  final String id;
  final String name;
  final String bundleId;
  final String? platform;

  const AppInfo({
    required this.id,
    required this.name,
    required this.bundleId,
    this.platform,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ bundleId.hashCode ^ platform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          bundleId == other.bundleId &&
          platform == other.platform;
}

/// The full App Info detail for an app: the app-info resource's own ids and
/// category/age-rating wiring, merged with the owning app's `sku`,
/// `primary_locale`, and `content_rights_declaration`. `localizations` reuses the
/// sibling [`AppInfoLocalizationInfo`] record, and `age_rating` carries the
/// resolved [`AgeRatingDeclarationInfo`] when present in the JSON:API `included`
/// section. The category ids are resolved from the app-info resource's
/// relationships (not its attributes). All optional fields are `None` when the
/// corresponding attribute / relationship is absent.
class AppInfoDetails {
  final String appInfoId;
  final String appId;
  final String? sku;
  final String? primaryLocale;
  final String? contentRightsDeclaration;
  final String? primaryCategoryId;
  final String? primarySubcategoryOneId;
  final String? secondaryCategoryId;
  final String? secondarySubcategoryOneId;
  final String? ageRatingDeclarationId;
  final String? appStoreAgeRating;
  final List<AppInfoLocalizationInfo> localizations;
  final AgeRatingDeclarationInfo? ageRating;

  const AppInfoDetails({
    required this.appInfoId,
    required this.appId,
    this.sku,
    this.primaryLocale,
    this.contentRightsDeclaration,
    this.primaryCategoryId,
    this.primarySubcategoryOneId,
    this.secondaryCategoryId,
    this.secondarySubcategoryOneId,
    this.ageRatingDeclarationId,
    this.appStoreAgeRating,
    required this.localizations,
    this.ageRating,
  });

  @override
  int get hashCode =>
      appInfoId.hashCode ^
      appId.hashCode ^
      sku.hashCode ^
      primaryLocale.hashCode ^
      contentRightsDeclaration.hashCode ^
      primaryCategoryId.hashCode ^
      primarySubcategoryOneId.hashCode ^
      secondaryCategoryId.hashCode ^
      secondarySubcategoryOneId.hashCode ^
      ageRatingDeclarationId.hashCode ^
      appStoreAgeRating.hashCode ^
      localizations.hashCode ^
      ageRating.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfoDetails &&
          runtimeType == other.runtimeType &&
          appInfoId == other.appInfoId &&
          appId == other.appId &&
          sku == other.sku &&
          primaryLocale == other.primaryLocale &&
          contentRightsDeclaration == other.contentRightsDeclaration &&
          primaryCategoryId == other.primaryCategoryId &&
          primarySubcategoryOneId == other.primarySubcategoryOneId &&
          secondaryCategoryId == other.secondaryCategoryId &&
          secondarySubcategoryOneId == other.secondarySubcategoryOneId &&
          ageRatingDeclarationId == other.ageRatingDeclarationId &&
          appStoreAgeRating == other.appStoreAgeRating &&
          localizations == other.localizations &&
          ageRating == other.ageRating;
}

/// An App Store app-info localization, keyed by `locale`. Carries the per-locale
/// App Store listing metadata: the `name` and `subtitle` shown on the product
/// page, plus the three privacy links/text (`privacy_policy_url`,
/// `privacy_choices_url`, `privacy_policy_text`). All attributes are optional;
/// App Store Connect serializes them camelCase (`privacyPolicyUrl`,
/// `privacyChoicesUrl`, `privacyPolicyText`), which `rename_all = "camelCase"`
/// maps without any per-field rename.
class AppInfoLocalizationInfo {
  final String id;
  final String locale;
  final String? name;
  final String? subtitle;
  final String? privacyPolicyUrl;
  final String? privacyChoicesUrl;
  final String? privacyPolicyText;

  const AppInfoLocalizationInfo({
    required this.id,
    required this.locale,
    this.name,
    this.subtitle,
    this.privacyPolicyUrl,
    this.privacyChoicesUrl,
    this.privacyPolicyText,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      locale.hashCode ^
      name.hashCode ^
      subtitle.hashCode ^
      privacyPolicyUrl.hashCode ^
      privacyChoicesUrl.hashCode ^
      privacyPolicyText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfoLocalizationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          locale == other.locale &&
          name == other.name &&
          subtitle == other.subtitle &&
          privacyPolicyUrl == other.privacyPolicyUrl &&
          privacyChoicesUrl == other.privacyChoicesUrl &&
          privacyPolicyText == other.privacyPolicyText;
}

/// The App Store version "App Review Information" detail: the app-review contact
/// (name, email, phone), optional demo account credentials, and reviewer notes
/// surfaced at submission time. App Store Connect exposes exactly one per version
/// (the singular `appStoreReviewDetail` relationship). All attributes are
/// optional. This is version-scoped, distinct from [`BetaAppReviewDetailInfo`]
/// (which is the TestFlight/app-scoped beta review detail).
class AppReviewDetailInfo {
  final String id;
  final String? contactFirstName;
  final String? contactLastName;
  final String? contactEmail;
  final String? contactPhone;
  final String? notes;
  final String? demoAccountName;
  final String? demoAccountPassword;
  final bool? isDemoAccountRequired;

  const AppReviewDetailInfo({
    required this.id,
    this.contactFirstName,
    this.contactLastName,
    this.contactEmail,
    this.contactPhone,
    this.notes,
    this.demoAccountName,
    this.demoAccountPassword,
    this.isDemoAccountRequired,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      contactFirstName.hashCode ^
      contactLastName.hashCode ^
      contactEmail.hashCode ^
      contactPhone.hashCode ^
      notes.hashCode ^
      demoAccountName.hashCode ^
      demoAccountPassword.hashCode ^
      isDemoAccountRequired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppReviewDetailInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contactFirstName == other.contactFirstName &&
          contactLastName == other.contactLastName &&
          contactEmail == other.contactEmail &&
          contactPhone == other.contactPhone &&
          notes == other.notes &&
          demoAccountName == other.demoAccountName &&
          demoAccountPassword == other.demoAccountPassword &&
          isDemoAccountRequired == other.isDemoAccountRequired;
}

/// An App Store version localization, keyed by `locale`. Carries the per-locale
/// version listing metadata shown on the product page: `description`, `keywords`,
/// `promotional_text`, the `support_url`/`marketing_url` links, and the
/// `whats_new` release notes. App Store Connect serializes the URL/notes
/// attributes camelCase (`promotionalText`, `supportUrl`, `marketingUrl`,
/// `whatsNew`), which `rename_all = "camelCase"` maps without any per-field
/// rename. All attributes are optional and are `None` when absent.
class AppStoreLocalizationInfo {
  final String id;
  final String? locale;
  final String? description;
  final String? keywords;
  final String? promotionalText;
  final String? supportUrl;
  final String? marketingUrl;
  final String? whatsNew;

  const AppStoreLocalizationInfo({
    required this.id,
    this.locale,
    this.description,
    this.keywords,
    this.promotionalText,
    this.supportUrl,
    this.marketingUrl,
    this.whatsNew,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      locale.hashCode ^
      description.hashCode ^
      keywords.hashCode ^
      promotionalText.hashCode ^
      supportUrl.hashCode ^
      marketingUrl.hashCode ^
      whatsNew.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStoreLocalizationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          locale == other.locale &&
          description == other.description &&
          keywords == other.keywords &&
          promotionalText == other.promotionalText &&
          supportUrl == other.supportUrl &&
          marketingUrl == other.marketingUrl &&
          whatsNew == other.whatsNew;
}

/// An App Store version of an app. Dates are raw ISO8601 strings; the core does
/// no date parsing (the host owns that).
class AppStoreVersionInfo {
  final String id;
  final String appId;
  final String? platform;
  final String? appStoreState;
  final String? appVersionState;
  final String? versionString;
  final String? copyright;
  final String? releaseType;
  final String? createdDate;

  const AppStoreVersionInfo({
    required this.id,
    required this.appId,
    this.platform,
    this.appStoreState,
    this.appVersionState,
    this.versionString,
    this.copyright,
    this.releaseType,
    this.createdDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      appId.hashCode ^
      platform.hashCode ^
      appStoreState.hashCode ^
      appVersionState.hashCode ^
      versionString.hashCode ^
      copyright.hashCode ^
      releaseType.hashCode ^
      createdDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStoreVersionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          appId == other.appId &&
          platform == other.platform &&
          appStoreState == other.appStoreState &&
          appVersionState == other.appVersionState &&
          versionString == other.versionString &&
          copyright == other.copyright &&
          releaseType == other.releaseType &&
          createdDate == other.createdDate;
}

/// A TestFlight app-level localization, keyed by `locale`. `feedback_email` is
/// the per-locale address testers' feedback is sent to, and `description` is the
/// per-locale TestFlight test description shown to testers.
class BetaAppLocalizationInfo {
  final String id;
  final String locale;
  final String? feedbackEmail;
  final String? description;

  const BetaAppLocalizationInfo({
    required this.id,
    required this.locale,
    this.feedbackEmail,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      locale.hashCode ^
      feedbackEmail.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BetaAppLocalizationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          locale == other.locale &&
          feedbackEmail == other.feedbackEmail &&
          description == other.description;
}

/// The TestFlight "Test Information" beta review detail for an app: the beta
/// review contact (name, email, phone), optional demo account credentials, and
/// reviewer notes. App Store Connect exposes exactly one per app (the singular
/// `betaAppReviewDetail` relationship). All attributes are optional.
class BetaAppReviewDetailInfo {
  final String id;
  final String? contactFirstName;
  final String? contactLastName;
  final String? contactEmail;
  final String? contactPhone;
  final String? demoAccountName;
  final String? demoAccountPassword;
  final bool? isDemoAccountRequired;
  final String? notes;

  const BetaAppReviewDetailInfo({
    required this.id,
    this.contactFirstName,
    this.contactLastName,
    this.contactEmail,
    this.contactPhone,
    this.demoAccountName,
    this.demoAccountPassword,
    this.isDemoAccountRequired,
    this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      contactFirstName.hashCode ^
      contactLastName.hashCode ^
      contactEmail.hashCode ^
      contactPhone.hashCode ^
      demoAccountName.hashCode ^
      demoAccountPassword.hashCode ^
      isDemoAccountRequired.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BetaAppReviewDetailInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contactFirstName == other.contactFirstName &&
          contactLastName == other.contactLastName &&
          contactEmail == other.contactEmail &&
          contactPhone == other.contactPhone &&
          demoAccountName == other.demoAccountName &&
          demoAccountPassword == other.demoAccountPassword &&
          isDemoAccountRequired == other.isDemoAccountRequired &&
          notes == other.notes;
}

/// A TestFlight "What to Test" localization for a single build, keyed by
/// `locale`. `whats_new` carries the per-locale testing notes shown to testers.
class BetaBuildLocalizationInfo {
  final String id;
  final String locale;
  final String? whatsNew;

  const BetaBuildLocalizationInfo({
    required this.id,
    required this.locale,
    this.whatsNew,
  });

  @override
  int get hashCode => id.hashCode ^ locale.hashCode ^ whatsNew.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BetaBuildLocalizationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          locale == other.locale &&
          whatsNew == other.whatsNew;
}

/// A TestFlight beta group (internal or external) of an app. Dates are raw
/// ISO8601 strings; the core does no date parsing (the host owns that).
class BetaGroupInfo {
  final String id;
  final String appId;
  final String? name;
  final String? createdDate;
  final bool? isInternalGroup;
  final bool? hasAccessToAllBuilds;
  final bool? publicLinkEnabled;
  final String? publicLink;
  final bool? feedbackEnabled;

  const BetaGroupInfo({
    required this.id,
    required this.appId,
    this.name,
    this.createdDate,
    this.isInternalGroup,
    this.hasAccessToAllBuilds,
    this.publicLinkEnabled,
    this.publicLink,
    this.feedbackEnabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      appId.hashCode ^
      name.hashCode ^
      createdDate.hashCode ^
      isInternalGroup.hashCode ^
      hasAccessToAllBuilds.hashCode ^
      publicLinkEnabled.hashCode ^
      publicLink.hashCode ^
      feedbackEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BetaGroupInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          appId == other.appId &&
          name == other.name &&
          createdDate == other.createdDate &&
          isInternalGroup == other.isInternalGroup &&
          hasAccessToAllBuilds == other.hasAccessToAllBuilds &&
          publicLinkEnabled == other.publicLinkEnabled &&
          publicLink == other.publicLink &&
          feedbackEnabled == other.feedbackEnabled;
}

/// A TestFlight beta tester. `invite_type` and `state` are the raw ASC values
/// passed through verbatim; the core does no remapping.
class BetaTesterInfo {
  final String id;
  final String? firstName;
  final String? lastName;
  final String? email;
  final String? inviteType;
  final String? state;

  const BetaTesterInfo({
    required this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.inviteType,
    this.state,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      firstName.hashCode ^
      lastName.hashCode ^
      email.hashCode ^
      inviteType.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BetaTesterInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          email == other.email &&
          inviteType == other.inviteType &&
          state == other.state;
}

/// The full detail of a single build: the enriched [`BuildInfo`] plus its
/// associated beta groups and per-locale "What to Test" localizations, all
/// resolved from the JSON:API `included` section of the build document.
class BuildDetailInfo {
  final BuildInfo build;
  final List<BetaGroupInfo> betaGroups;
  final List<BetaBuildLocalizationInfo> localizations;

  const BuildDetailInfo({
    required this.build,
    required this.betaGroups,
    required this.localizations,
  });

  @override
  int get hashCode =>
      build.hashCode ^ betaGroups.hashCode ^ localizations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildDetailInfo &&
          runtimeType == other.runtimeType &&
          build == other.build &&
          betaGroups == other.betaGroups &&
          localizations == other.localizations;
}

/// A build (TestFlight / App Store Connect) of an app. `version` is the build
/// number (the ASC `version` attribute, distinct from a version string). Dates
/// are raw ISO8601 strings; the core does no date parsing (the host owns that).
///
/// Beyond the build's own attributes this record also carries enrichment
/// resolved from JSON:API `included` related resources — the marketing version
/// and platform (from `preReleaseVersion`), the external/internal build states
/// and auto-notify flag (from `buildBetaDetail`), and the beta review state and
/// submission date (from `betaAppReviewSubmission`). These enrichment fields are
/// only populated when the corresponding relationship is requested via `include`
/// (and present); they are `None` otherwise. `icon_url` is computed from the
/// build's `iconAssetToken` template.
class BuildInfo {
  final String id;
  final String appId;
  final String? version;
  final String? uploadedDate;
  final bool? expired;
  final String? processingState;
  final String? minOsVersion;
  final String? expirationDate;

  /// From included `preReleaseVersion.attributes.version`.
  final String? marketingVersion;

  /// From included `preReleaseVersion.attributes.platform`.
  final String? platform;

  /// From included `buildBetaDetail.attributes.externalBuildState`.
  final String? externalBuildState;

  /// From included `buildBetaDetail.attributes.internalBuildState`.
  final String? internalBuildState;

  /// From included `buildBetaDetail.attributes.autoNotifyEnabled`.
  final bool? autoNotifyEnabled;

  /// From included `betaAppReviewSubmission.attributes.betaReviewState`.
  final String? betaReviewState;

  /// From included `betaAppReviewSubmission.attributes.submittedDate` (raw ISO8601).
  final String? submittedDate;

  /// Build attribute `computedMinMacOsVersion`.
  final String? computedMinMacOsVersion;

  /// Build attribute `computedMinVisionOsVersion`.
  final String? computedMinVisionOsVersion;

  /// Build attribute `buildAudienceType`.
  final String? buildAudienceType;

  /// Build attribute `usesNonExemptEncryption`.
  final bool? usesNonExemptEncryption;

  /// Computed from the build's `iconAssetToken` template (`{w}`/`{h}`/`{f}`
  /// substituted). `None` when no template URL is present.
  final String? iconUrl;

  const BuildInfo({
    required this.id,
    required this.appId,
    this.version,
    this.uploadedDate,
    this.expired,
    this.processingState,
    this.minOsVersion,
    this.expirationDate,
    this.marketingVersion,
    this.platform,
    this.externalBuildState,
    this.internalBuildState,
    this.autoNotifyEnabled,
    this.betaReviewState,
    this.submittedDate,
    this.computedMinMacOsVersion,
    this.computedMinVisionOsVersion,
    this.buildAudienceType,
    this.usesNonExemptEncryption,
    this.iconUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      appId.hashCode ^
      version.hashCode ^
      uploadedDate.hashCode ^
      expired.hashCode ^
      processingState.hashCode ^
      minOsVersion.hashCode ^
      expirationDate.hashCode ^
      marketingVersion.hashCode ^
      platform.hashCode ^
      externalBuildState.hashCode ^
      internalBuildState.hashCode ^
      autoNotifyEnabled.hashCode ^
      betaReviewState.hashCode ^
      submittedDate.hashCode ^
      computedMinMacOsVersion.hashCode ^
      computedMinVisionOsVersion.hashCode ^
      buildAudienceType.hashCode ^
      usesNonExemptEncryption.hashCode ^
      iconUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          appId == other.appId &&
          version == other.version &&
          uploadedDate == other.uploadedDate &&
          expired == other.expired &&
          processingState == other.processingState &&
          minOsVersion == other.minOsVersion &&
          expirationDate == other.expirationDate &&
          marketingVersion == other.marketingVersion &&
          platform == other.platform &&
          externalBuildState == other.externalBuildState &&
          internalBuildState == other.internalBuildState &&
          autoNotifyEnabled == other.autoNotifyEnabled &&
          betaReviewState == other.betaReviewState &&
          submittedDate == other.submittedDate &&
          computedMinMacOsVersion == other.computedMinMacOsVersion &&
          computedMinVisionOsVersion == other.computedMinVisionOsVersion &&
          buildAudienceType == other.buildAudienceType &&
          usesNonExemptEncryption == other.usesNonExemptEncryption &&
          iconUrl == other.iconUrl;
}

/// One page of builds plus an opaque token to fetch the next page. `next_token`
/// is `None` on the last page; otherwise pass it back verbatim as the next call's
/// `page_token` (it is the JSON:API `links.next` URL). Mirrors
/// [`CustomerReviewsPage`].
class BuildsPage {
  final List<BuildInfo> builds;
  final String? nextToken;

  const BuildsPage({required this.builds, this.nextToken});

  @override
  int get hashCode => builds.hashCode ^ nextToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildsPage &&
          runtimeType == other.runtimeType &&
          builds == other.builds &&
          nextToken == other.nextToken;
}

/// A capability enabled on a bundle ID (e.g. `PUSH_NOTIFICATIONS`,
/// `FONT_INSTALLATION`, `CARPLAY_CHARGING`).
///
/// `capability_type` is the raw ASC `capabilityType` string, forwarded verbatim:
/// App Store Connect keeps adding values, so the core never models it as a closed
/// enum. The wire-mapping boundary skips resources whose `capabilityType` is
/// missing or empty.
class BundleIdCapabilityInfo {
  final String id;
  final String capabilityType;

  const BundleIdCapabilityInfo({
    required this.id,
    required this.capabilityType,
  });

  @override
  int get hashCode => id.hashCode ^ capabilityType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BundleIdCapabilityInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          capabilityType == other.capabilityType;
}

/// A bundle ID (App ID) registered for the connected App Store Connect account.
///
/// `identifier`, `name`, and `platform` are non-optional with an empty-string
/// fallback applied at the wire-mapping boundary when the attribute is absent;
/// `seed_id` is optional (the ASC `seedId` attribute). `platform` is the raw ASC
/// `BundleIdPlatform` value (`IOS`, `MAC_OS`, or `UNIVERSAL`), forwarded without
/// remapping.
class BundleIdInfo {
  final String id;
  final String identifier;
  final String name;
  final String platform;
  final String? seedId;

  const BundleIdInfo({
    required this.id,
    required this.identifier,
    required this.name,
    required this.platform,
    this.seedId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      identifier.hashCode ^
      name.hashCode ^
      platform.hashCode ^
      seedId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BundleIdInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          identifier == other.identifier &&
          name == other.name &&
          platform == other.platform &&
          seedId == other.seedId;
}

/// A signing certificate registered for the connected App Store Connect account
/// (development, distribution, push, Pass Type ID, or Apple Pay merchant
/// certificate).
///
/// `display_name`, `name`, and `certificate_type` are non-optional with an
/// empty-string fallback applied at the wire-mapping boundary when the attribute
/// is absent; `platform`, `serial_number`, and `expiration_date` are optional.
/// `certificate_type` is the raw ASC `CertificateType` value (e.g.
/// `IOS_DEVELOPMENT`, `IOS_DISTRIBUTION`, `MAC_APP_DISTRIBUTION`), forwarded
/// without remapping. `expiration_date` is the raw ISO8601 string passed through
/// verbatim — the core does no date parsing.
///
/// `is_activated` maps the ASC `activated` attribute (note the wire key is
/// `activated`, not `isActivated`). `certificate_content` is the base64-encoded
/// certificate payload: it is `None` for list results (the list omits it) and
/// `Some` after a create or single-resource fetch.
class CertificateInfo {
  final String id;
  final String displayName;
  final String name;
  final String certificateType;
  final String? platform;
  final String? serialNumber;
  final String? expirationDate;
  final bool isActivated;
  final String? certificateContent;

  const CertificateInfo({
    required this.id,
    required this.displayName,
    required this.name,
    required this.certificateType,
    this.platform,
    this.serialNumber,
    this.expirationDate,
    required this.isActivated,
    this.certificateContent,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      name.hashCode ^
      certificateType.hashCode ^
      platform.hashCode ^
      serialNumber.hashCode ^
      expirationDate.hashCode ^
      isActivated.hashCode ^
      certificateContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CertificateInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          name == other.name &&
          certificateType == other.certificateType &&
          platform == other.platform &&
          serialNumber == other.serialNumber &&
          expirationDate == other.expirationDate &&
          isActivated == other.isActivated &&
          certificateContent == other.certificateContent;
}

/// A single end-user App Store review, optionally with the developer's response.
/// Dates are raw ISO8601 strings; the core does no date parsing.
class CustomerReview {
  final String id;
  final int rating;
  final String? title;
  final String? body;
  final String? reviewerNickname;
  final String? createdDate;
  final String? territory;
  final ReviewResponse? response;

  const CustomerReview({
    required this.id,
    required this.rating,
    this.title,
    this.body,
    this.reviewerNickname,
    this.createdDate,
    this.territory,
    this.response,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rating.hashCode ^
      title.hashCode ^
      body.hashCode ^
      reviewerNickname.hashCode ^
      createdDate.hashCode ^
      territory.hashCode ^
      response.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomerReview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rating == other.rating &&
          title == other.title &&
          body == other.body &&
          reviewerNickname == other.reviewerNickname &&
          createdDate == other.createdDate &&
          territory == other.territory &&
          response == other.response;
}

/// One page of customer reviews plus an opaque token to fetch the next page.
/// `next_token` is `None` on the last page; otherwise pass it back verbatim as
/// the next call's `page_token` (it is the JSON:API `links.next` URL).
class CustomerReviewsPage {
  final List<CustomerReview> reviews;
  final String? nextToken;

  const CustomerReviewsPage({required this.reviews, this.nextToken});

  @override
  int get hashCode => reviews.hashCode ^ nextToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomerReviewsPage &&
          runtimeType == other.runtimeType &&
          reviews == other.reviews &&
          nextToken == other.nextToken;
}

/// A registered device of the connected App Store Connect account (a development
/// device used for provisioning). `name` and `status` are non-optional with sane
/// fallbacks (`""` and `"ENABLED"`) applied at the wire-mapping boundary when the
/// attribute is absent; the remaining attributes are optional.
///
/// `platform` is the raw ASC `BundleIdPlatform` value (`IOS`, `MAC_OS`, or
/// `UNIVERSAL`); `status` is the raw ASC device status (`ENABLED` or `DISABLED`).
/// `device_class` mirrors the ASC `deviceClass` attribute and `added_date` the
/// `addedDate` attribute — a raw ISO8601 string passed through verbatim (the host
/// owns any date parsing). All raw ASC strings are forwarded without remapping.
class DeviceInfo {
  final String id;
  final String name;
  final String? udid;
  final String? platform;
  final String? deviceClass;
  final String? model;
  final String status;
  final String? addedDate;

  const DeviceInfo({
    required this.id,
    required this.name,
    this.udid,
    this.platform,
    this.deviceClass,
    this.model,
    required this.status,
    this.addedDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      udid.hashCode ^
      platform.hashCode ^
      deviceClass.hashCode ^
      model.hashCode ^
      status.hashCode ^
      addedDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          udid == other.udid &&
          platform == other.platform &&
          deviceClass == other.deviceClass &&
          model == other.model &&
          status == other.status &&
          addedDate == other.addedDate;
}

/// An App Store version's phased (staged) release. App Store Connect exposes
/// exactly one per version via the singular `appStoreVersionPhasedRelease`
/// relationship. `state` carries the raw ASC `phasedReleaseState` value
/// (`INACTIVE` / `ACTIVE` / `PAUSED` / `COMPLETE`) — the record field is named
/// `state` even though the attribute is `phasedReleaseState`. `start_date` is a
/// raw ISO8601 string; the core does no date parsing (the host owns that). All
/// optional fields are `None` when the corresponding attribute is absent.
class PhasedReleaseInfo {
  final String id;
  final String? state;
  final String? startDate;
  final int? totalPauseDuration;
  final int? currentDayNumber;

  const PhasedReleaseInfo({
    required this.id,
    this.state,
    this.startDate,
    this.totalPauseDuration,
    this.currentDayNumber,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      state.hashCode ^
      startDate.hashCode ^
      totalPauseDuration.hashCode ^
      currentDayNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhasedReleaseInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          state == other.state &&
          startDate == other.startDate &&
          totalPauseDuration == other.totalPauseDuration &&
          currentDayNumber == other.currentDayNumber;
}

/// A provisioning profile registered for the connected App Store Connect
/// account, pairing a bundle ID with the certificates (and, for development
/// profiles, the devices) it authorizes.
///
/// `name`, `profile_type`, and `profile_state` are non-optional with an
/// empty-string fallback applied at the wire-mapping boundary when the attribute
/// is absent; `platform`, `uuid`, `bundle_id`, `created_date`, and
/// `expiration_date` are optional. `profile_type` is the raw ASC `profileType`
/// value (e.g. `IOS_APP_DEVELOPMENT`, `IOS_APP_STORE`, `MAC_APP_STORE`),
/// forwarded without remapping; `profile_state` is the raw `profileState` value
/// (e.g. `ACTIVE`, `INVALID`).
///
/// `bundle_id` is the RESOLVED bundle identifier string (e.g. `com.acme.app`),
/// looked up from the JSON:API `included[]` bundleIds by the profile's
/// `bundleId` relationship id — not the relationship id itself. It is `None` when
/// the profile carries no `bundleId` relationship, when the referenced bundle ID
/// is absent from `included[]`, or on the create path (the host does not resolve
/// it there).
///
/// `created_date` and `expiration_date` are raw ISO8601 strings passed through
/// verbatim — the core does no date parsing. `profile_content` is the base64-
/// encoded `.mobileprovision` payload: it is `None` for list results (the list
/// omits it) and `Some` after a create or single-resource content fetch.
class ProvisioningProfileInfo {
  final String id;
  final String name;
  final String profileType;
  final String profileState;
  final String? platform;
  final String? uuid;
  final String? bundleId;
  final String? createdDate;
  final String? expirationDate;
  final String? profileContent;

  const ProvisioningProfileInfo({
    required this.id,
    required this.name,
    required this.profileType,
    required this.profileState,
    this.platform,
    this.uuid,
    this.bundleId,
    this.createdDate,
    this.expirationDate,
    this.profileContent,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      profileType.hashCode ^
      profileState.hashCode ^
      platform.hashCode ^
      uuid.hashCode ^
      bundleId.hashCode ^
      createdDate.hashCode ^
      expirationDate.hashCode ^
      profileContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProvisioningProfileInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          profileType == other.profileType &&
          profileState == other.profileState &&
          platform == other.platform &&
          uuid == other.uuid &&
          bundleId == other.bundleId &&
          createdDate == other.createdDate &&
          expirationDate == other.expirationDate &&
          profileContent == other.profileContent;
}

/// The developer's response attached to a [`CustomerReview`]. Dates are raw
/// ISO8601 strings; the core does no date parsing (the host owns that).
class ReviewResponse {
  final String id;
  final String? body;
  final String? state;
  final String? lastModifiedDate;

  const ReviewResponse({
    required this.id,
    this.body,
    this.state,
    this.lastModifiedDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^ body.hashCode ^ state.hashCode ^ lastModifiedDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          body == other.body &&
          state == other.state &&
          lastModifiedDate == other.lastModifiedDate;
}

/// A single App Store screenshot. `image_url` is computed from the screenshot's
/// `imageAsset` template (`{w}`/`{h}`/`{f}` substituted, defaulting to 512/512/png),
/// exactly as the build icon URL is; it is `None` when no template URL is present.
/// `width`/`height` come from the `imageAsset` dimensions, and `file_name` /
/// `file_size` from the screenshot's own attributes. All optional fields are
/// `None` when the corresponding attribute is absent.
class ScreenshotInfo {
  final String id;
  final String? imageUrl;
  final String? fileName;
  final int? fileSize;
  final int? width;
  final int? height;

  const ScreenshotInfo({
    required this.id,
    this.imageUrl,
    this.fileName,
    this.fileSize,
    this.width,
    this.height,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      imageUrl.hashCode ^
      fileName.hashCode ^
      fileSize.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScreenshotInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          imageUrl == other.imageUrl &&
          fileName == other.fileName &&
          fileSize == other.fileSize &&
          width == other.width &&
          height == other.height;
}

/// A set of App Store screenshots for a single device display type within a
/// version localization. `display_type` carries the raw ASC
/// `screenshotDisplayType` value (e.g. `APP_IPHONE_67`) passed through verbatim,
/// and `screenshots` lists the set's screenshots in the relationship order
/// reported by App Store Connect.
class ScreenshotSetInfo {
  final String id;
  final String? displayType;
  final List<ScreenshotInfo> screenshots;

  const ScreenshotSetInfo({
    required this.id,
    this.displayType,
    required this.screenshots,
  });

  @override
  int get hashCode => id.hashCode ^ displayType.hashCode ^ screenshots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScreenshotSetInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayType == other.displayType &&
          screenshots == other.screenshots;
}

/// A team member of the connected App Store Connect account: the lightweight
/// projection of a `users` resource carrying only `first_name`/`last_name`, the
/// `username` (App Store Connect stores the member's login email here), and the
/// raw ASC `roles` strings (e.g. `"ADMIN"`, `"DEVELOPER"`, `"APP_MANAGER"`),
/// passed through verbatim without remapping. `first_name`/`last_name`/
/// `username` are optional; `roles` is empty when absent.
class TeamMemberInfo {
  final String id;
  final String? firstName;
  final String? lastName;
  final String? username;
  final List<String> roles;

  const TeamMemberInfo({
    required this.id,
    this.firstName,
    this.lastName,
    this.username,
    required this.roles,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      firstName.hashCode ^
      lastName.hashCode ^
      username.hashCode ^
      roles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TeamMemberInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          username == other.username &&
          roles == other.roles;
}

/// A user of the connected App Store Connect account, unifying two ASC
/// resources: active members (`users`) and outstanding invitations
/// (`userInvitations`). `is_pending` discriminates the source — `false` for an
/// active member, `true` for a pending invitation. For active members `email`
/// is taken from the `username` attribute (App Store Connect stores the login
/// email there) and `expiration_date` is always `None`; for pending invitations
/// `email` is the invitation's own `email` and `expiration_date` is the raw
/// ISO8601 expiry (host owns parsing). `roles` carries the raw ASC role strings
/// verbatim; `all_apps_visible` and `provisioning_allowed` default to `false`
/// when the attribute is absent.
class UserInfo {
  final String id;
  final String? firstName;
  final String? lastName;
  final String? email;
  final List<String> roles;
  final bool allAppsVisible;
  final bool provisioningAllowed;
  final bool isPending;
  final String? expirationDate;

  const UserInfo({
    required this.id,
    this.firstName,
    this.lastName,
    this.email,
    required this.roles,
    required this.allAppsVisible,
    required this.provisioningAllowed,
    required this.isPending,
    this.expirationDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      firstName.hashCode ^
      lastName.hashCode ^
      email.hashCode ^
      roles.hashCode ^
      allAppsVisible.hashCode ^
      provisioningAllowed.hashCode ^
      isPending.hashCode ^
      expirationDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          email == other.email &&
          roles == other.roles &&
          allAppsVisible == other.allAppsVisible &&
          provisioningAllowed == other.provisioningAllowed &&
          isPending == other.isPending &&
          expirationDate == other.expirationDate;
}
