// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Cross-provider app metadata. Mirrors the Swift `AppInfo` from `StackProtocols`,
/// which is dissolved into the core (see RUST_CORE_PLAN.md §4).
///
/// Serializes camelCase (`bundleId`, not `bundle_id`) so persisted blobs match the
/// iOS-facing contract — see [`crate::service::sync::SyncService`].
class AppInfo {
  final String id;
  final String name;
  final String bundleId;
  final String? platform;

  const AppInfo({
    required this.id,
    required this.name,
    required this.bundleId,
    this.platform,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ bundleId.hashCode ^ platform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          bundleId == other.bundleId &&
          platform == other.platform;
}

/// A single end-user App Store review, optionally with the developer's response.
/// Dates are raw ISO8601 strings; the core does no date parsing.
class CustomerReview {
  final String id;
  final int rating;
  final String? title;
  final String? body;
  final String? reviewerNickname;
  final String? createdDate;
  final String? territory;
  final ReviewResponse? response;

  const CustomerReview({
    required this.id,
    required this.rating,
    this.title,
    this.body,
    this.reviewerNickname,
    this.createdDate,
    this.territory,
    this.response,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rating.hashCode ^
      title.hashCode ^
      body.hashCode ^
      reviewerNickname.hashCode ^
      createdDate.hashCode ^
      territory.hashCode ^
      response.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomerReview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rating == other.rating &&
          title == other.title &&
          body == other.body &&
          reviewerNickname == other.reviewerNickname &&
          createdDate == other.createdDate &&
          territory == other.territory &&
          response == other.response;
}

/// One page of customer reviews plus an opaque token to fetch the next page.
/// `next_token` is `None` on the last page; otherwise pass it back verbatim as
/// the next call's `page_token` (it is the JSON:API `links.next` URL).
class CustomerReviewsPage {
  final List<CustomerReview> reviews;
  final String? nextToken;

  const CustomerReviewsPage({required this.reviews, this.nextToken});

  @override
  int get hashCode => reviews.hashCode ^ nextToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomerReviewsPage &&
          runtimeType == other.runtimeType &&
          reviews == other.reviews &&
          nextToken == other.nextToken;
}

/// The developer's response attached to a [`CustomerReview`]. Dates are raw
/// ISO8601 strings; the core does no date parsing (the host owns that).
class ReviewResponse {
  final String id;
  final String? body;
  final String? state;
  final String? lastModifiedDate;

  const ReviewResponse({
    required this.id,
    this.body,
    this.state,
    this.lastModifiedDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^ body.hashCode ^ state.hashCode ^ lastModifiedDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          body == other.body &&
          state == other.state &&
          lastModifiedDate == other.lastModifiedDate;
}
