// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class StackError with _$StackError implements FrbException {
  const StackError._();

  const factory StackError.invalidCredentials({required String message}) =
      StackError_InvalidCredentials;
  const factory StackError.auth({required String message}) = StackError_Auth;
  const factory StackError.pendingAgreements({required String message}) =
      StackError_PendingAgreements;
  const factory StackError.http({
    required int status,
    required String message,
  }) = StackError_Http;
  const factory StackError.decode({required String message}) =
      StackError_Decode;
  const factory StackError.network({required String message}) =
      StackError_Network;
  const factory StackError.unsupported({required String message}) =
      StackError_Unsupported;
}
