// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'domain.dart';
import 'error.dart';
import 'frb_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'service/kind.dart';
import 'service/provider.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FrbProviderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FrbReviewsPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FrbSyncServicePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FrbProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    dynamic raw,
  );

  @protected
  FrbReviews
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    dynamic raw,
  );

  @protected
  FrbSyncService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    dynamic raw,
  );

  @protected
  FrbProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    dynamic raw,
  );

  @protected
  FrbReviews
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    dynamic raw,
  );

  @protected
  FrbSyncService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(String)
  dco_decode_DartFn_Inputs_String_Output_unit_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(String, String, String)
  dco_decode_DartFn_Inputs_String_String_String_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  FrbProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    dynamic raw,
  );

  @protected
  FrbReviews
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    dynamic raw,
  );

  @protected
  FrbSyncService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppInfo dco_decode_app_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FrbReviews
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    dynamic raw,
  );

  @protected
  ReviewResponse dco_decode_box_autoadd_review_response(dynamic raw);

  @protected
  Capability dco_decode_capability(dynamic raw);

  @protected
  CredentialField dco_decode_credential_field(dynamic raw);

  @protected
  CustomerReview dco_decode_customer_review(dynamic raw);

  @protected
  CustomerReviewsPage dco_decode_customer_reviews_page(dynamic raw);

  @protected
  FrbCredential dco_decode_frb_credential(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AppInfo> dco_decode_list_app_info(dynamic raw);

  @protected
  List<Capability> dco_decode_list_capability(dynamic raw);

  @protected
  List<CredentialField> dco_decode_list_credential_field(dynamic raw);

  @protected
  List<CustomerReview> dco_decode_list_customer_review(dynamic raw);

  @protected
  List<FrbCredential> dco_decode_list_frb_credential(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ServiceKind> dco_decode_list_service_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FrbReviews?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    dynamic raw,
  );

  @protected
  ReviewResponse? dco_decode_opt_box_autoadd_review_response(dynamic raw);

  @protected
  ReviewResponse dco_decode_review_response(dynamic raw);

  @protected
  ServiceKind dco_decode_service_kind(dynamic raw);

  @protected
  StackError dco_decode_stack_error(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  FrbProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    SseDeserializer deserializer,
  );

  @protected
  FrbReviews
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    SseDeserializer deserializer,
  );

  @protected
  FrbSyncService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    SseDeserializer deserializer,
  );

  @protected
  FrbProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    SseDeserializer deserializer,
  );

  @protected
  FrbReviews
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    SseDeserializer deserializer,
  );

  @protected
  FrbSyncService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  FrbProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    SseDeserializer deserializer,
  );

  @protected
  FrbReviews
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    SseDeserializer deserializer,
  );

  @protected
  FrbSyncService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FrbReviews
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    SseDeserializer deserializer,
  );

  @protected
  ReviewResponse sse_decode_box_autoadd_review_response(
    SseDeserializer deserializer,
  );

  @protected
  Capability sse_decode_capability(SseDeserializer deserializer);

  @protected
  CredentialField sse_decode_credential_field(SseDeserializer deserializer);

  @protected
  CustomerReview sse_decode_customer_review(SseDeserializer deserializer);

  @protected
  CustomerReviewsPage sse_decode_customer_reviews_page(
    SseDeserializer deserializer,
  );

  @protected
  FrbCredential sse_decode_frb_credential(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AppInfo> sse_decode_list_app_info(SseDeserializer deserializer);

  @protected
  List<Capability> sse_decode_list_capability(SseDeserializer deserializer);

  @protected
  List<CredentialField> sse_decode_list_credential_field(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomerReview> sse_decode_list_customer_review(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbCredential> sse_decode_list_frb_credential(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ServiceKind> sse_decode_list_service_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FrbReviews?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    SseDeserializer deserializer,
  );

  @protected
  ReviewResponse? sse_decode_opt_box_autoadd_review_response(
    SseDeserializer deserializer,
  );

  @protected
  ReviewResponse sse_decode_review_response(SseDeserializer deserializer);

  @protected
  ServiceKind sse_decode_service_kind(SseDeserializer deserializer);

  @protected
  StackError sse_decode_stack_error(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    FrbProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    FrbReviews self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    FrbSyncService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    FrbProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    FrbReviews self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    FrbSyncService self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_String_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    FrbProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    FrbReviews self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    FrbSyncService self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    FrbReviews self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_review_response(
    ReviewResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capability(Capability self, SseSerializer serializer);

  @protected
  void sse_encode_credential_field(
    CredentialField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_customer_review(
    CustomerReview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_customer_reviews_page(
    CustomerReviewsPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_credential(FrbCredential self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_info(List<AppInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_capability(
    List<Capability> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_credential_field(
    List<CredentialField> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_customer_review(
    List<CustomerReview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_credential(
    List<FrbCredential> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_service_kind(
    List<ServiceKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    FrbReviews? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_review_response(
    ReviewResponse? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_review_response(
    ReviewResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_service_kind(ServiceKind self, SseSerializer serializer);

  @protected
  void sse_encode_stack_error(StackError self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbProvider(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbReviews(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbSyncService(
    int ptr,
  );
}
