// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'service/kind.dart';

/// Every service the core can connect today, for the Dart host's service picker.
///
/// Calls the same real core logic as the UniFFI facade
/// ([`crate::facade::available_services`]) — `registry::available_services()` —
/// and hands the result to the FRB binding. FRB mirrors [`ServiceKind`] into a
/// matching Dart enum, so the Dart side receives the real value from real core
/// code.
///
/// # Examples
///
/// ```
/// # use stack_core::frb_api::available_services;
/// # use stack_core::ServiceKind;
/// assert_eq!(available_services(), vec![ServiceKind::AppStoreConnect]);
/// ```
List<ServiceKind> availableServices() =>
    RustLib.instance.api.crateFrbApiAvailableServices();
