// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A capability a provider may expose. The host calls [`Provider::capabilities`]
/// to learn what a connected account can do; capabilities a provider lacks make
/// the corresponding accessor (e.g. [`Provider::reviews`]) return `None`. Grows
/// over time.
enum Capability {
  apps,
  reviews,
  appStoreVersions,
  builds,
  betaGroups,
  betaBuildLocalizations,
  betaAppLocalizations,
  betaAppReviewDetail,
  appMetadata,
  accessibilityDeclarations,
  users,
  devices,
  bundleIds,
  certificates,
  profiles,
}
